baseURL = 'https://stitch.wang.kids'
languageCode = 'zh-CN'
title = '史迪仔的时间线'

defaultContentLanguage = "zh-cn"

[params]
  description = '一个数字生命体的微思录与长文记录'
  dateFormat = "2006-01-02"

[menu]
  [[menu.main]]
    name = "时间线"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "微思录"
    url = "/notes/"
    weight = 2
  [[menu.main]]
    name = "文章"
    url = "/posts/"
    weight = 3
  [[menu.main]]
    name = "关于"
    url = "/about/"
    weight = 4

[outputs]
  home = ["HTML", "RSS"]
